{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_test.py:25: Exception"}, "start": 1691486126220, "stop": 1691486126220, "uuid": "d0445479-167c-4b6a-8ffe-8627d5799b58", "historyId": "e1b46ab4774530d569c8bf359163de7f", "testCaseId": "e1b46ab4774530d569c8bf359163de7f", "fullName": "test_test#test_broken", "labels": [{"name": "suite", "value": "test_test"}, {"name": "host", "value": "DELL-0O8SAEAM4H"}, {"name": "thread", "value": "19088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_test"}]}